import { expect, test } from "@playwright/test";

test("中文夹具窗口无横向溢出，并展示五个固定输入行", async ({ page }) => {
  await page.goto("http://127.0.0.1:1425");
  await expect(page.locator("html")).toHaveAttribute("lang", "zh-CN");
  await expect(page.getByRole("heading", { name: "VentureD Companion" })).toBeVisible();
  await expect(page.getByLabel("固定输入映射").locator(".mapping")).toHaveCount(5);
  await expect(page.getByText("GPIO8 外接确认/动作按钮", { exact: true })).toBeVisible();
  await expect(page.getByText("GPIO10 下拉按键", { exact: true })).toBeVisible();
  await expect(page.getByText("GPIO11 下拉按键", { exact: true })).toBeVisible();
  await expect(page.locator(".state")).toHaveText("已停止");
  await expect(page.getByRole("button", { name: "为本次运行启用实时模式" })).toBeDisabled();
  await expect(page.getByText("尚未捕获。请先切到目标应用，再点 3 秒后捕获。")).toBeVisible();
  await expect(page.getByRole("button", { name: "设置 未连接" })).toBeVisible();
  await expect(page.getByLabel("设备连接")).toBeVisible();
  await expect(page.getByText("已插入")).toBeVisible();
  await expect(page.getByLabel("转写结果")).toBeVisible();
  await expect(page.getByText("可录音")).toBeVisible();
  await expect(page.getByText("说完后，转写会出现在这里。")).toBeVisible();
  await expect(page.locator(".net")).toHaveText("未连接");
  await expect(page.getByText("Wi-Fi 名称")).toHaveCount(0);
  const initialText = await page.locator("body").innerText();
  expect(initialText).not.toMatch(/Hook|Codex 项目目录|检查 Hook/);
  for (const formerEnglishText of ["Disconnected", "Select a port", "Clockwise", "Counterclockwise", "Encoder press", "Last event"]) {
    expect(initialText).not.toContain(formerEnglishText);
  }
  await expect(page).toHaveScreenshot("companion-fixture.png", { fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBeTruthy();

  await expect(page.getByLabel("设备连接")).toBeVisible();
  await expect(page.getByText("插入即可连接，无需选择串口")).toBeVisible();
  await expect(page.getByText("已插入")).toBeVisible();
  await expect(page.getByText("请选择串口")).toHaveCount(0);
  await page.getByRole("button", { name: "3 秒后捕获" }).click();
  await page.getByRole("button", { name: "保存配置" }).click();
  await expect(page.getByRole("button", { name: "启动演练模式" })).toBeEnabled();
  await page.getByRole("button", { name: "启动演练模式" }).click();
  await expect(page.locator(".state")).toHaveText("演练模式");
  await expect(page.getByText("ENCODER_CW → CTRL+TAB · 演练模式")).toBeVisible();
  await expect(page.getByRole("button", { name: "为本次运行启用实时模式" })).toBeDisabled();
  await page.getByRole("button", { name: "停止运行" }).click();
  await expect(page.locator(".state")).toHaveText("已停止");
  await page.getByRole("button", { name: "顺时针旋转 快捷键" }).click();
  await expect(page.getByRole("button", { name: "顺时针旋转 快捷键" })).toHaveAttribute("aria-pressed", "true");
  await page.keyboard.down("Control");
  await page.keyboard.down("Tab");
  await page.keyboard.down("1");
  await page.keyboard.up("1");
  await page.keyboard.up("Tab");
  await page.keyboard.up("Control");
  await expect(page.getByRole("button", { name: "顺时针旋转 快捷键" })).toHaveText("CTRL+TAB+1");
  await expect(page.getByText("快捷键已更新；保存配置后才会用于派发。")).toBeVisible();

  await page.getByRole("button", { name: /设置/ }).click();
  await expect(page.getByText("开发板只支持 2.4GHz Wi-Fi")).toBeVisible();
  await page.getByLabel("Wi-Fi 名称").fill("cafe");
  await page.getByRole("textbox", { name: "Wi-Fi 密码" }).fill("secret");
  await expect(page.getByLabel("SiliconFlow API Key")).toBeVisible();
  await expect(page.getByLabel("转写模型")).toBeVisible();
  await expect(page.getByText("API Key 可留空")).toBeVisible();
  await expect(page.getByText(/GPIO9 仍可按住/)).toBeVisible();
  await expect(page.getByText(/GPIO16 人体感应/)).toBeVisible();
  await expect(page.getByRole("button", { name: "显示Wi-Fi 密码" })).toBeVisible();
  await page.getByRole("button", { name: "保存并下发联网" }).click();
  await expect(page.getByText("设备已联网。")).toBeVisible();
  await expect(page.getByText("已连接 10.0.0.8")).toBeVisible();
  await expect(page.getByRole("button", { name: "显示Wi-Fi 密码" })).toBeVisible();
  await page.getByRole("button", { name: "显示Wi-Fi 密码" }).click();
  await expect(page.getByRole("textbox", { name: "Wi-Fi 密码" })).toHaveValue("secret");
  await expect(page.getByRole("textbox", { name: "Wi-Fi 密码" })).toHaveAttribute("type", "text");
  await page.getByLabel("Wi-Fi 名称").fill("Home-5G");
  await expect(page.getByRole("alert").filter({ hasText: "当前名称像 5G 热点" })).toBeVisible();
  await page.getByRole("button", { name: "保存并下发联网" }).click();
  await expect(page.locator(".net")).toHaveText("失败 · 仅2.4G");
});
