:project:
  :build_root: build
  :which_ceedling: gem
:paths:
  :test:
    - test
  :source:
    - ../main/input
    - ../main/protocol
    - ../main/display
  :include:
    - ../main
    - ../main/input
    - ../main/protocol
    - ../main/display
:plugins:
  :enabled:
    - module_generator
