:project:
  :build_root: build
  :which_ceedling: gem
:paths:
  :test:
    - test
  :source:
    - ../main/input
    - ../main/protocol
    - ../main/display
  :include:
    - ../main
    - ../main/input
    - ../main/protocol
    - ../main/display
    - ../main/audio
:files:
  :source:
    - ../main/audio/pcm_metrics.c
    - ../main/audio/wav_pcm.c
:plugins:
  :enabled:
    - module_generator
